FROM base

RUN apt-get update
RUN apt-get install -y netcat

COPY weights/yolov5s-face.pth weights/yolov5s-face.pth

COPY torchserve/ torchserve/

COPY models models

COPY utils utils

COPY torch2trt torch2trt
#RUN git clone https://github.com/NVIDIA-AI-IOT/torch2trt

RUN cd torch2trt && python3 setup.py install && cd .. && rm -rf torch2trt

RUN python3 ./torchserve/model_repack.py --trt 1 # 依赖GPU，模型转trt格式，需要一分钟

EXPOSE 8080 8081 8082 7070 7071

RUN chmod +x ./torchserve/run.sh

ENTRYPOINT ["./torchserve/run.sh"]
