FROM nvcr.io/nvidia/tensorrt:20.12-py3

ARG VERSION_TORCH2TRT=0.3.0

WORKDIR /build
COPY . .

RUN python3 -m pip install pip --upgrade && \
    python3 -m pip install -r requirements.txt && \
    cd /tmp && \
    wget https://github.com/NVIDIA-AI-IOT/torch2trt/archive/refs/heads/v${VERSION_TORCH2TRT}.zip -O torch2trt-${VERSION_TORCH2TRT}.zip && \
    unzip torch2trt-${VERSION_TORCH2TRT}.zip && \
    cd torch2trt-${VERSION_TORCH2TRT} && \
    python3 setup.py install && \
    cd /tmp && rm -rf * && \
    cd /build && \
    python3 ./torchserve/model_repack.py --trt 1
